baseURL = 'https://sysym.dev/'
languageCode = 'id-ID'
title = 'sysym.dev'
enableRobotsTXT = true

[permalinks]
  posts = '/:title'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    tabWidth = 2
    pygmentsCodeFences = true
    pygmentsUseClasses = true

[params]
  description = 'Kumpulan Catatan Coding dan Berbagai Artikel Seputar Coding'
  authorName = 'Ibrahim Al Anshor'
  authorURL = 'https://ibrahimalanshor.github.io'

[taxonomies]
  tag = 'tags'

[menu]
[[menu.main]]
  name = 'About'
  url = '/about/'
[[menu.main]]
  name = 'Posts'
  url = '/posts/'
[[menu.main]]
  name = 'Tags'
  url = '/tags/'

[outputs]
  home = ['html', 'json', 'rss']