baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'sysym.dev'
enableRobotsTXT = true

[permalinks]
  posts = '/:title'

[markup.highlight]
  noClasses = false

[params]
  description = 'Kumpulan Catatan Coding dan Berbagai Artikel Seputar Coding'
  authorName = 'Ibrahim Al Anshor'
  authorURL = 'https://ibrahimalanshor.github.io'
  googleSiteVerification = 'LeQXvrWLrnsIYD3glynvhfiBr7PEYQNqqaQhI8vscBE'

[taxonomies]
  tag = 'tags'

[menu]
[[menu.main]]
  name = 'About'
  url = '/about/'
[[menu.main]]
  name = 'Posts'
  pageRef = '/posts'
[[menu.main]]
  name = 'Tags'
  pageRef = '/tags'
